### ISSUE TITLE
Interested in i18n?

### ISSUE THREAD

**Issue by floscher** [osmlab/josm-atlas#12]
Would you be interested in putting the translatable strings of this plugin on Transifex to allow translation to other languages?

Now that you use the gradle-josm-plugin, this shouldn't be hard to set up.

**Comment by hallahan** [comment]
We would appreciate this. A PR will be welcome!

**Comment by floscher** [comment]
:+1: I'm preparing a PR for this and #8, should be ready soon.

Do you already have a Transifex account? This change will need an API token for Transifex. I'd then add you to the JOSM organization on Transifex, so you get the right to upload resources.

In the build script there are hints to Maven publishing but it doesn't seem to be set up. Are you planning to also publish to a Maven repo? It wouldn't play well with the plugin update mechanism of JOSM. JOSM always takes the filename without extension as plugin name. In Maven repos the filename also contains the version number.
