### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by hallahan** [osmlab/josm-atlas#7]
We now have a better way of building via Gradle. It would be good to update these instructions.

**Comment by floscher** [comment]
I updated the build instructions in 4e7243d97fff63cb862b5c1798f8502ac400a2e1, these should be pretty much up to date.

**Comment by hallahan** [comment]
Thanks, since we are going to have josm-atlas be a regular JOSM plugin, we don't need to provide a link to the JAR.
