### ISSUE TITLE
Add josm-atlas to standard JOSM plugins list.

### ISSUE THREAD

**Issue by hallahan** [osmlab/josm-atlas#8]
It will be nice to just download this plugin using the standard JOSM plugin list mechanism, rather than requiring the user to build it themselves.

**Comment by floscher** [comment]
The easiest way is probably to publish GitHub releases and put a link to that file into https://josm.openstreetmap.de/wiki/PluginsSource .

I could prepare a PR soon, that would set Travis CI up to publish a *.jar file to GitHub each time a git-tag is pushed to this repo (I did already set that up for several other JOSM plugins).

**Comment by hallahan** [comment]
Yes, that would be awesome! It would be very much appreciated!
